# Deep Learning - Introduction
***

Deep learning is learning based on data representations rather than traditional task-specific algorithms. It is structured/hierarchical learning and is part of a broader family of machine learning methods. Deep Learning can be supervised, semi-supervised or unsupervised

![title](img/deeplearning.png)
Source: http://www.deeplearningbook.org/contents/intro.html

![title](img/whydeeplearning.png)
Source: deeplearning.ai


** Concepts and Projects that are done after intoduction**
* Create Neural network using algorithms like gradient descent, backpropgation to train the model with python and use Sentiment Analysis to evaluate and validate model. Project1: To predict Bike-sharing patterns on a given day

* Create convolutional networks to build an autoencoder, a network architecture used for image compression and denoising using PyTorch. Project2: Classify dog breeds in pictures

* Create recurrent neural network and combain with word embeddings that can generate new text, character by character. Project3: Generate new TV scripts from provided, existing scripts

* Implement Generative Adversarial Networks for various tasks using Cycle GAN. Project4: Use a deep convolutional GAN to generate completely new images of human faces

* Deploying machine learning models on a cloud and monitor using PyTorch and Amazon's SageMaker. Project5: Deploy PyTorch sentiment analysis model and create a gateway for accessing this model from a website

** Data Dimensions **
* Scalers: Zero dimensional Tensor like age, height etc
* Vectors: One dimensional Tensor .It stores list of values
* Matrices: Two dimensional Tensor. It stores grid of values
* Tensor: Two + dimensional Tensor. It stores collection of values

 Every object we make (vectors, matrices, tensors) eventually stores scalars

** NumPy **

In [1]:
import numpy as np 

# Creating numpy array with scaler object
s = np.array(5)

In [2]:
# when we check the shape of the scaler we can notice empty parenthesis
# This indicates it has zero dimensions
s.shape

()

In [3]:
# Even though scalars are inside arrays, you still use them like a normal scalar
x = s+3

In [4]:
type(x)

numpy.int32

In [5]:
x.shape

()

In [6]:
# Vectors
v = np.array([1,2,3])

In [8]:
#It returns a single number representing the vector's one-dimensional length
v.shape

(3,)

In [9]:
#Can access an element within the vector using indices
v[2]

3

In [10]:
v[1:]

array([2, 3])

In [11]:
# Matrices
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [12]:
m.shape

(3, 3)

In [13]:
m[1][2]

6

In [14]:
# Tensors
# 3x3x2x1 tensor, you could do the following
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [15]:
t.shape

(3, 3, 2, 1)

** Changing shapes **

In [16]:
v = np.array([1,2,3,4])

In [17]:
v.shape

(4,)

In [18]:
# reshape
x=v.reshape(1,4)

In [20]:
x.shape

(1, 4)

In [21]:
y=v.reshape(4,1)

In [22]:
y.shape

(4, 1)

In [25]:
# instead of using reshape, we can do
z = v[None,:]

In [26]:
z

array([[1, 2, 3, 4]])

In [27]:
z1 = v[:,None]

In [28]:
z1

array([[1],
       [2],
       [3],
       [4]])

** Numpy Additions **

In [32]:
#Python Element wise operation
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
print (values)

[6, 7, 8, 9, 10]


In [35]:
# Numpy Element wise operation
values = [1,2,3,4,5]
values = np.array(values) + 5
print(values)

[ 6  7  8  9 10]


In [37]:
# if the values are already in array format
values += 5
print(values)

[16 17 18 19 20]


** Numpy Multiplicaiton **

In [40]:
# Element-wise Multiplication
# Accomplish this with the multiply function or the * operator
m = np.array([[1,2,3],[4,5,6]])
n = m * 0.5

In [41]:
n

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [42]:
m* n

array([[ 0.5,  2. ,  4.5],
       [ 8. , 12.5, 18. ]])

In [43]:
# OR we can use multiply
np.multiply(m,n)

array([[ 0.5,  2. ,  4.5],
       [ 8. , 12.5, 18. ]])

In [47]:
# Matrix Product
# Use NumPy's matmul function
# Two matrix's should in be compatible shapes
# i.e, mXn and nXo. 
# number of columns of first matrix should be equal to number of rows of second matrix
# If your matrices have incompatible shapes, you'll get an error
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

for i in [a,b]:
    print(i.shape)

(2, 4)
(4, 3)


we can notice that number of columns of first matrix is equal to number of rows of second matrix 

In [48]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [49]:
c.shape

(2, 3)

In [50]:
# NumPy's dot function
# Results of dot and matmul are the same if the matrices are two dimensional
a = np.array([[1,2],[3,4]])
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [51]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [52]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

** Transposes in Numpy **

* We can safely use a Transpose in a Matrix Multiplication if the data in both of the origial matrices is arranged in rows
* Use T attribute or transpose() function

In [54]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [57]:
# OR
np.transpose(m)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Note: If we modify transposed matrix, it will modify both the transpose and the original matrix

In [58]:
# Example
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

for i in [inputs,weights]:
    print(i.shape)

(1, 4)
(3, 4)


Matrix product of these two matrices will give an error. So lets transpose one matrix

In [60]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [61]:
# Or we can transpose second matrix and swap
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

The two answers are transposes of each other, so which multiplication you use really just depends on the shape you want for the output.

In [62]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    # We can use NumPy's min function and element-wise division
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    # We can use NumPy's max function and element-wise division
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # Check the shapes of the matrices m1 and m2. 
    # m1 and m2 will be ndarray objects.
    #
    # Return False if the shapes cannot be used for matrix
    # multiplication. You may not use a transpose
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:     
        return False

    # Have not returned False, so calculate the matrix product
    # of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)        
    else:
        return np.matmul(m2, m1)        


def find_mean(values):
    # Return the average of the values in the given Python list
    # NumPy has a lot of helpful methods like this.
    return np.mean(values)

In [63]:
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
